name: flutter_tagging_plus
description: A flutter package with tagging or multiselect functionality. Useful for adding Tag or Label Selection Forms.
version: 4.1.0
repository: https://github.com/waqas-JT/flutter_tagging_plus


environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead:
    git: 
      url: https://github.com/waqas-JT/flutter_typeahead
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

publish_to: none
